"Error receiving message: '_thread._local' object has no attribute 'value'"